name: Check GCP action
on:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v2.1.3'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/gcp-labs-3xo24suq/locations/global/workloadIdentityPools/iam-lab-7-gh-pool/providers/iam-lab-7-gh-pool-oidc-provider'
          service_account: 'iam-lab-7-target@gcp-labs-3xo24suq.iam.gserviceaccount.com'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud config set project gcp-labs-3xo24suq
        gcloud config set account 'iam-lab-7-target@gcp-labs-3xo24suq.iam.gserviceaccount.com'
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud auth list
        gcloud projects list
